version: '3'

services:
  backend:
    build: .
    container_name: "backend"
    command: ["flask", "run"]
    depends_on: 
      - celery
      - database
    environment:
      FLASK_APP: "app.py"
      FLASK_RUN_HOST: "0.0.0.0"
      REDIS_HOST: "redis"
      WDB_SOCKET_SERVER: wdb
      QBITTORRENT_HOST: "qbittorrent"
      QBITTORRENT_USERNAME: "admin"
      QBITTORRENT_PASSWORD: "adminadmin"
    ports:
      - "5000:5000"

  redis:
    image: "redis:alpine"

  database:
    image: "postgres"
    environment: 
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"

  celery:
    build: .
    container_name: "celery"
    depends_on: 
      - database
      - redis
      - qbittorrent
    environment:
      WDB_SOCKET_SERVER: wdb
      REDIS_HOST: "redis"
      QBITTORRENT_HOST: "qbittorrent"
      QBITTORRENT_USERNAME: "admin"
      QBITTORRENT_PASSWORD: "adminadmin"
    command: ["celery", "worker", "-A", "tasks", "--loglevel=info"]

  qbittorrent:
    image: linuxserver/qbittorrent:100
    container_name: qbittorrent
    environment:
      PUID: 1000
      PGID: 1000
      TZ: Europe/London
      UMASK_SET: 022
      WEBUI_PORT: 8080
    volumes:
       - /tmp/qbittorrent_downloads:/downloads
       - /tmp/qbittorrent_config:/config
       - H:\movies:/downloads/movies
       - H:\movies:/downloads/tv_shows
    ports:
      - 6881:6881
      - 6881:6881/udp
      - 8080:8080
    restart: unless-stopped

  plex:
    image: linuxserver/plex
    container_name: plex
    network_mode: host
    environment:
      - VERSION=docker
    ports:
      - 32400:32400/tcp
      - 3005:3005/tcp
      - 8324:8324/tcp
      - 32469:32469/tcp
      - 1900:1900/udp
      - 32410:32410/udp
      - 32412:32412/udp
      - 32413:32413/udp
      - 32414:32414/udp
    volumes:
      - /tmp/plex_config:/config
      - /tmp/media/tv_shows:/data/tv_shows
      - H:\movies:/data/movies
      - /tmp/transcode:/transcode
    restart: unless-stopped

  wdb:
    image: kozea/wdb:3.2.5
    ports:
      - "1984:1984"

volumes:
  qbittorrent_config:
