# Generated by Django 2.0.4 on 2018-08-18 00:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0002_auto_20180815_0127'),
    ]

    operations = [
        migrations.AddField(
            model_name='torrent',
            name='magnet',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
