# Generated by Django 2.0.4 on 2018-08-18 01:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0003_torrent_magnet'),
    ]

    operations = [
        migrations.AddField(
            model_name='torrent',
            name='download_path',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
