# Generated by Django 2.0.4 on 2018-08-26 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0005_season_completed'),
    ]

    operations = [
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('value', models.TextField()),
            ],
        ),
    ]
