# Generated by Django 2.0.4 on 2018-08-26 22:12

from django.db import migrations


def create_config(apps, schema_editor):
    Configuration = apps.get_model('video', 'Configuration')
    configs = {
        "download_path": "/tmp/",
        "yts_url": "https://yts.am/api/v2",
        "tpb_url": "https://thepiratebay.org/"
    }
    for config_name, config_value in configs.items():
        Configuration(name=config_name, value=config_value).save()


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0006_configuration'),
    ]

    operations = [
        migrations.RunPython(create_config),
    ]
