# Generated by Django 2.0.4 on 2018-08-27 23:23

from django.db import migrations


def create_config(apps, schema_editor):
    Configuration = apps.get_model('video', 'Configuration')
    configs = {
        "base_download_path": "/tmp/",
        "movies_sub_path": "peliculas",
        "tv_shows_sub_path": "series"
    }
    for config_name, config_value in configs.items():
        Configuration(name=config_name, value=config_value).save()


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0007_auto_20180826_2212'),
    ]

    operations = [
        migrations.RunPython(create_config),
    ]
