# Generated by Django 2.0.4 on 2018-09-02 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0008_auto_20180827_2323'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='download_path',
        ),
        migrations.AlterField(
            model_name='configuration',
            name='name',
            field=models.TextField(unique=True),
        ),
    ]
