# Generated by Django 2.0.4 on 2018-12-22 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0009_auto_20180902_1713'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='year',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterUniqueTogether(
            name='season',
            unique_together={('number', 'video')},
        ),
    ]
