# Generated by Django 2.0.4 on 2018-12-22 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0010_auto_20181222_1423'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='video',
            unique_together={('name', 'year')},
        ),
    ]
